export type ColorPalette = {
  bg: string;
  bg_dark: string;
  bg_highlight: string;
  fg: string;
  fg_dark: string;
  fg_gutter: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  purple: string;
  cyan: string;
  orange: string;
  error: string;
  warning: string;
  info: string;
  hint: string;
  dark_gray: string;
  gray: string;
  light_gray: string;
  selection: string;
};
